### PR TITLE
add missing connect by name check

### PR DESCRIPTION
**Pull request by damdamce**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :smiley:

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by iamsergio** [comment]
thanks, I'll have a look, no need to go through phab

**Comment by iamsergio** [comment]
Usually I only update the README before a release, but I've updated it now, thanks.

**Comment by damdamce** [comment]
oh, right. I forgot to switch to the tag after cloning. will do..

thanks..

**Pull request closed without merging**
