### PR TITLE
range-loop: Added note about unhelpful warning

### PR DESCRIPTION
**Pull request by bjorn**

### CODE REVIEW

**Comment by iamsergio** [comment]
maybe this is fixable in clazy

**Comment by bjorn** [comment]
> maybe this is fixable in clazy

Sure, if a fix is doable then this is preferable to merging this note. I suggested to add a note since many of the other checks have potential issues or false positives documented as well.

**Comment by bjorn** [comment]
It appears that the use of `auto` suppresses this warning. This snippet does trigger it:
```c++
    QJsonArray array;
    for (const QJsonValue a : array) {}
```

**Comment by bjorn** [comment]
I have no idea how the comment I just made has been made "7 hours ago".

**Comment by bjorn** [comment]
"iamsergio commented 6 hours _from now_" :S

**Comment by iamsergio** [comment]
> ```c++
> for (const QJsonValue a : array) {}
> ```

range-loop is still technically correct, just not the best warning message ever.
You're creating unneeded temporary QJsonValue instances, and instead, should use it by ref, 
which for QJsonArray means:

for (QJsonValueRef a : array) {}

Fixing it in clazy itself would add overhead for a rare edge case, so maybe updating the README might be best

**Comment by bjorn** [comment]
> for (QJsonValueRef a : array) {}

That only works if `array` is non-const, for `const QJsonArray`, that would trigger:

    error: no viable conversion from 'QJsonValue' to 'const QJsonValueRef'

Since [`QJsonValueRef`](https://doc.qt.io/qt-5/qjsonvalue.html#qjsonvalueref) exists only to allow in-place modification of the value.

So the snippet that triggers on `range-loop` in an unhelpful way is actually:

```c++
    const QJsonArray array;
    for (const QJsonValue a : array) {}
```

**Comment by iamsergio** [comment]
For the const case, adding & compiles just fine.

        const QJsonArray array;
        for (const QJsonValue &v : array) {}

Which compiler (and version) is giving you -Wrange-loop-analysis ?
I have to investigate who's right

**Comment by iamsergio** [comment]
I've tried clang -Wrange-loop-analysis (clang 8), and it doesn't emit any warning for:

    const QJsonArray const_array;
    for (const QJsonValue &a : const_array) {}

**Comment by iamsergio** [comment]
The only case that makes -Wrange-loop-analysis trigger is:

    QJsonArray array;
    for (const QJsonValue &a : array) {}

which we've seen that should be fixed by using QJsonValueRef

**Comment by bjorn** [comment]
> The only case that makes -Wrange-loop-analysis trigger is:

You're completely right. I must have added the `const` in a kind of automated fashion when I first ran into this issue. So indeed, range-loop triggers appropriately in both the const and non-const cases, and in case we really want non-const iteration we need to use QJsonValueRef.

Sorry for the confusion and thanks for patience!

**Pull request closed without merging**
